[package]
name = "fuzz_bench"
version = "0.1.0"
authors = ["Philip Woolford <woolford.philip@gmail.com>"]

[dependencies]
smallvec = "0.6"

[dev-dependencies]
criterion = "0.2"

[[bench]]
name = "mine"
harness = false

